name: adaptIpynbFiles

on:
  push:
    # Notebook files could only come in through notebooks* or InputNotebooks*
    #branches:
    #- 'main'
   paths:
     - 'notebooks/**/*'
     - 'InputNotebooks/**/*'
  pull_request:
    branches:
      - main
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cleanFiles:
    runs-on: ubuntu-latest  
    name: Apply_Nbconvert_2_ipynb_files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: install nbconvert
        run: python -m pip install jupyter nbconvert nbformat

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24.1
          #with:
          #separator: ";"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [[ $file == *.ipynb ]]
            then
              # clear output on all .ipynb files for diff'ing 
              echo "$file is an ipynb file"
              jupyter nbconvert --to notebook --ClearOutputPreprocessor.enabled=True --inplace $file
              if [[ $file == *solution.ipynb ]]
              then    
                # execute solutions files inplace
                echo "$file is an solution file"
                jupyter nbconvert --to notebook --execute --inplace $file
              fi
            else
              echo "$file is not an ipynb file"
            fi
          done

      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
 

