# This workflow will build a new docker image 
# and upload it to christadler/seismo-live
# It will only run if a release is made or
# if the workflow is dipatched by hand
#
# Author: Iris Christadler
# Last modified: 2022-09-07

name: deploy2

on:
  release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v2
        name: Check out code

      - id: builddocker
        uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: christadler/test_action
          registry: docker.io
          dockerfile: docker/Dockerfile.test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: printName
        run: |
          echo "FROM christadler/test_action:"${{steps.builddocker.outputs.tags}} > Dockerfile.iris

      - id: Commit
        uses: EndBug/add-and-commit@v9
        name: commit updated notebook
        with:
          add: 'Dockerfile.iris'
          message: "Added link to newly created dockerimage" 
          committer_name: GitHub Actions
          committer_email: actions@github.com
