# This workflow will build a new docker image 
# and upload it to christadler/seismo-live
# It will only run if a release is made or
# if the workflow is dipatched by hand
#
# Author: Iris Christadler
# Last modified: 2022-09-07

name: deploy2

on:
  release:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      outputIN: ${{ steps.builddocker.outputs.imageName }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        name: Check out code

      - id: builddocker
        uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: christadler/seismo-live
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "::set-output name=test::hello"
      - id: step2
        run: echo "::set-output name=test::world"
  jobs2:
    runs-on: ubuntu-latest
    needs: [job1, docker]  
    steps: 
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
      - run: echo ${{needs.docker.outputs.outputIN}}
