# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  buildDockerimage:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: create html pages
        run: |
          jupyter kernelspec list
          jupyter nbconvert --to html --execute notebooks/**/*.ipynb --ExecutePreprocessor.kernel_name='python3' --output-dir html/
          pwd
          ls -al html/
          
  uploadDockerimage:

