# This file was used for testing
# It should be a starting point for the jupytext2ipynb workflow
# It is currently not ready for production
# author: Iris Christadler

name: (nip) jupytext2ipynb

on:
  push:
    paths:
      - 'InputNotebooks/**/*'
  pull_request:
    branches: 
      - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  strip:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: install nbconvert
        run: python -m pip install jupyter nbconvert nbformat

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24.1

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            if [[ $file == *.py ]]
            then
              # convert to notebook
              echo "$file is an .py file, converting with jupytext --to notebook"
              # Convert jupytext to notebook with no outputs
              jupytext --to notebook $file
            else
              echo "$file is not an .py file"
            fi
          done

      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com


