# This is a basic workflow to help you get started with Actions

name: jupytext2ipynb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  strip:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip -r requirements.txt
          python -m pip install jupyter nbconvert nbformat
        
      - name: Update analysis notebook
        run: |
          jupyter nbconvert --to notebook --execute notebooks/Python_Crash_Course_solution.ipynb --ExecutePreprocessor.kernel_name='python3' --output ../notebooks_executed/{{ filename }}_solution.ipynbtational Seismology/Wave Propagation & Analytical Solutions/time_reversal_reciprocity.py
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Plot update bot
          message: "Update Notebook"
          add: "notebook_executed.ipynb"

      # This part will only try to build the docker image
      # It will not push it to hub.docker.com
      # There is another basic actions that helps with publishing
      # https://github.com/actions/starter-workflows/blob/main/ci/docker-publish.yml     
      #- name: Build the Docker image
      # run: docker build . --file Dockerfile --tag christadler/seismo-live:$(date +%s)


