# This github action workflow will convert all notebooks found in /notebooks
# to the html directory
# 
# Author: Iris Christadler
# Latest Update: 2022-08-10
name: (wip) Convert_2_HTML

on:
  #push:
    #branches:
    # - 'main'
    # Notebooks will only come in through /notebooks but it might make
    # more sense to issue this only by hand or on release
    #paths:
    #- '/notebooks/**/*'

  release:      
  
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  convert2html:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt

      - name: install nbconvert
        run: python -m pip install jupyter nbconvert nbformat
        
      - name: create html pages
        run: |
          jupyter kernelspec list
          echo "Converting all notebooks to HTML"
          jupyter nbconvert --to html --execute notebooks/**/*.ipynb --ExecutePreprocessor.kernel_name='python3' --output-dir html/
          ls -al html/*
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v9
        with:
          message: Show GitHub Actions logo
          committer_name: GitHub Actions
          committer_email: actions@github.com
