# This is a basic workflow to help you get started with Actions

name: nbconvert2html

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:
      - 'main'
    paths:
      - '/notebooks/**/*'
        
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  convert2html:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt
        
      - name: create html pages
        run: |
          jupyter kernelspec list
          jupyter nbconvert --to html --execute notebooks/Python\ Introduction/* --output-dir ../html/
          #jupyter nbconvert --to html --execute notebooks/Python\ Introduction/* --ExecutePreprocessor.kernel_name='python3' --output-dir ../html/
          
      - name: commit updated notebook
        uses: EndBug/add-and-commit@v7
        with:
          author_name: nbconvert2html-Action
          message: "Added html files"
